/* Copyright (c) 2026 - 2026, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("registry-maintainability", component_id, "Require package to be actively maintained.") :-
    check_passed(component_id, "mcn_registry_maintainability_1").

apply_policy_to("registry-maintainability", component_id) :-
    is_component(component_id, "pkg:pypi/boto@2.49.0").
