# Copyright (c) 2022 - 2025, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

"""This module processes the JSON dependency output files generated by CycloneDX Maven plugin.

It also collects the direct dependencies that should be processed by Macaron.
See https://github.com/CycloneDX/cyclonedx-maven-plugin.
"""

import logging
import os

from macaron.config.global_config import global_config
from macaron.dependency_analyzer.cyclonedx import DependencyAnalyzer

logger: logging.Logger = logging.getLogger(__name__)


class CycloneDxPython(DependencyAnalyzer):
    """This class implements the CycloneDX Maven plugin analyzer."""

    def get_cmd(self) -> list:
        """Return the CLI command to run the CycloneDX Maven plugin.

        Returns
        -------
        list
            The command line arguments.
        """
        logger.info(
            (
                "The SBOM generator has started resolving the dependencies and storing them in the %s file. "
                "This might take a while..."
            ),
            self.file_name,
        )
        return [
            "cyclonedx-py",
            "environment",
            global_config.python_venv_path,
            "--output-format",
            "json",
            "--output-file",
            os.path.join(global_config.output_path, self.file_name),
        ]
