# Copyright (c) 2022 - 2023, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

# This configuration file enables Dependabot version updates.
# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/about-dependabot-version-updates
# https://github.com/dependabot/feedback/issues/551

version: 2
updates:
- package-ecosystem: pip
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
  open-pull-requests-limit: 13
  target-branch: staging
  # Add additional reviewers for PRs opened by Dependabot. For more information, see:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers
  # reviewers:
  # -

- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
  open-pull-requests-limit: 13
  target-branch: staging
  # Add additional reviewers for PRs opened by Dependabot. For more information, see:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers
  # reviewers:
  # -

- package-ecosystem: gomod
  directory: /
  schedule:
    interval: weekly
  commit-message:
    prefix: chore
    prefix-development: chore
    include: scope
  open-pull-requests-limit: 13
  target-branch: staging
  # Add additional reviewers for PRs opened by Dependabot. For more information, see:
  # https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#reviewers
  # reviewers:
  # -
