/* Copyright (c) 2024 - 2024, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("slsa_verifier_policy", component_id, "Policy for SLSA Verifier") :-
  check_passed(component_id, "mcn_build_as_code_1"),
  check_passed(component_id, "mcn_provenance_level_three_1"),
  check_passed(component_id, "mcn_provenance_available_1").

apply_policy_to("slsa_verifier_policy", component_id) :-
  is_repo(
    _,  // repo_id
    "github.com/slsa-framework/slsa-verifier",
    component_id
  ).
