# Copyright (c) 2022 - 2026, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
default_install_hook_types: [pre-commit, commit-msg, pre-push]
default_stages: [pre-commit]
minimum_pre_commit_version: 4.0.0

repos:

# These meta hooks check the pre-commit configuration itself.
- repo: meta
  hooks:
  - id: check-hooks-apply
  - id: check-useless-excludes

# Commitizen enforces semantic and conventional commit messages.
- repo: https://github.com/commitizen-tools/commitizen
  rev: 2ca29f9297911f8f5a4e8f97100b7832f045e8d3  # frozen: v4.13.10
  hooks:
  - id: commitizen
    name: Check conventional commit message
    stages: [commit-msg]

# Sort imports.
- repo: https://github.com/pycqa/isort
  rev: dac090ce4d9ee313d086e2e89ab1acb8c2664fa1  # frozen: 9.0.0a3
  hooks:
  - id: isort
    name: Sort import statements
    args: [--settings-path, pyproject.toml]
    exclude: ^tests/malware_analyzer/pypi/resources/sourcecode_samples.*

# Add Black code formatters.
- repo: https://github.com/ambv/black
  rev: c6755bb741b6481d6b3d3bb563c83fa060db96c9  # frozen: v26.3.1
  hooks:
  - id: black
    name: Format code
    args: [--config, pyproject.toml, --target-version, py311]
    exclude: ^tests/malware_analyzer/pypi/resources/sourcecode_samples.*
- repo: https://github.com/asottile/blacken-docs
  rev: dda8db18cfc68df532abf33b185ecd12d5b7b326  # frozen: 1.20.0
  hooks:
  - id: blacken-docs
    name: Format code in docstrings
    args: [--line-length, '120']
    additional_dependencies: [black==26.3.1]

# Upgrade and rewrite Python idioms.
- repo: https://github.com/asottile/pyupgrade
  rev: 75992aaa40730136014f34227e0135f63fc951b4  # frozen: v3.21.2
  hooks:
  - id: pyupgrade
    name: Upgrade code idioms
    files: ^src/macaron/|^tests/
    args: [--py311-plus]

# Similar to pylint, with a few more/different checks. For more available
# extensions: https://github.com/DmytroLitvinov/awesome-flake8-extensions
- repo: https://github.com/pycqa/flake8
  rev: d93590f5be797aabb60e3b09f2f52dddb02f349f  # frozen: 7.3.0
  hooks:
  - id: flake8
    name: Check flake8 issues
    files: ^src/macaron/|^tests/
    types: [text, python]
    additional_dependencies: [flake8-bugbear==25.11.29, flake8-builtins==3.1.0, flake8-comprehensions==3.17.0, flake8-docstrings==1.7.0, flake8-logging==1.8.0, flake8-mutable==1.2.0, flake8-noqa==1.5.0, flake8-print==5.0.0, flake8-pytest-style==2.2.0, flake8-rst-docstrings==0.4.0, pep8-naming==0.15.1]
    exclude: ^tests/malware_analyzer/pypi/resources/sourcecode_samples.*
    args: [--config, .flake8]

# Check GitHub Actions workflow files.
- repo: https://github.com/Mateusz-Grzelinski/actionlint-py
  rev: c04ed26e40637cab1aa9879c693832a9c120fb20  # frozen: v1.7.12.24
  hooks:
  - id: actionlint

# Check shell scripts with shellcheck.
- repo: https://github.com/shellcheck-py/shellcheck-py
  rev: 745eface02aef23e168a8afb6b5737818efbea95  # frozen: v0.11.0.1
  hooks:
  - id: shellcheck
    exclude: ^tests/

# Run Pylint from the local repo to make sure venv packages
# specified in pyproject.toml are available.
- repo: local
  hooks:
  - id: pylint
    name: Check pylint issues
    entry: pylint
    language: python
    files: ^src/macaron/|^tests/
    exclude: ^tests/malware_analyzer/pypi/resources/sourcecode_samples.*
    types: [text, python]
    args: [--rcfile, pyproject.toml]

# Type-check all Python code.
- repo: local
  hooks:
  - id: mypy
    name: Check typing annotations
    entry: mypy
    language: python
    files: ^src/macaron/|^tests/
    types: [text, python]
    exclude: ^tests/malware_analyzer/pypi/resources/sourcecode_samples.*
    args: [--show-traceback, --config-file, pyproject.toml]

# Check for potential security issues.
- repo: https://github.com/PyCQA/bandit
  rev: 92ae8b82fb422a639f0ed8d99e96cea769594e08  # frozen: v1.9.4
  hooks:
  - id: bandit
    name: Check for security issues
    args: [--configfile, pyproject.toml]
    files: ^src/macaron/|^tests/
    types: [text, python]
    additional_dependencies: ['bandit[toml]']
    exclude: ^tests/malware_analyzer/pypi/resources/sourcecode_samples.*

# Enable a whole bunch of useful helper hooks, too.
# See https://pre-commit.com/hooks.html for more hooks.
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 3e8a8703264a2f4a69428a0aa4dcb512790b2c8c  # frozen: v6.0.0
  hooks:
  - id: check-ast
  - id: check-case-conflict
  - id: check-merge-conflict
  - id: debug-statements
  - id: end-of-file-fixer
    stages: [pre-commit]
  - id: trailing-whitespace
    args: [--markdown-linebreak-ext=md]
    stages: [pre-commit]
    exclude: ^tests/(.)*\.ambr$
  - id: detect-private-key
  - id: detect-aws-credentials
    args: [--allow-missing-credentials]
  - id: check-yaml
    args: [--allow-multiple-documents]
  - id: check-toml
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: 3a6eb0fadf60b3cccfd80bad9dbb6fae7e47b316  # frozen: v1.10.0
  hooks:
  - id: python-check-blanket-noqa
  # Disabling blanket-type-ignore for now until type stubs are added.
  # - id: python-check-blanket-type-ignore
  - id: python-check-mock-methods
  - id: python-use-type-annotations
  - id: rst-backticks
  - id: rst-directive-colons
  - id: rst-inline-touching-normal
  - id: text-unicode-replacement-char

# Check the reStructured Text files that make up
# this package's documentation.
# Commenting this out because https://github.com/Lucas-C/pre-commit-hooks-markup/issues/13
# - repo: https://github.com/Lucas-C/pre-commit-hooks-markup
#   rev: 501f3d60cee13c712492103343bc23efdc7b3d1f  # frozen: v1.0.1
#   hooks:
#   - id: rst-linter

# Check and prettify the configuration files.
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: 4380fbb73a154b5f5624794c1c78d9719ccc860f  # frozen: v2.16.0
  hooks:
  - id: pretty-format-ini
    args: [--autofix]
  - id: pretty-format-yaml
    args: [--autofix]
  # Commenting this out because https://github.com/pappasam/toml-sort/issues/11
  # - id: pretty-format-toml
  #   args: [--autofix]

- repo: local
  hooks:
  - id: integration-test-vet
    name: validate integration test cases
    entry: python
    args:
    - ./tests/integration/run.py
    - vet
    - ./tests/integration/cases/...
    language: system
    pass_filenames: false

# On push to the remote, run the unit tests.
- repo: local
  hooks:
  - id: pytest
    name: Run unit tests
    entry: |
      python -W always::DeprecationWarning -m pytest -c pyproject.toml --cov-config pyproject.toml
      src/macaron/ tests/ docs/
    language: system
    verbose: true
    always_run: true
    pass_filenames: false
    stages: [pre-push]

# Checks the copyright header for .js, .py, and .java, etc. files.
- repo: local
  hooks:
  - id: copyright-checker
    name: Copyright checker
    entry: scripts/dev_scripts/copyright-checker.sh
    language: system
    always_run: true
    pass_filenames: false

# Checks that tests/malware_analyzer/pypi/resources/sourcecode_samples files do not have executable permissions
# This is another measure to make sure the files can't be accidentally executed
- repo: local
  hooks:
  - id: sourcecode-sample-permissions
    name: Sourcecode sample executable permissions checker
    entry: scripts/dev_scripts/samples_permissions_checker.sh
    language: system
    always_run: true
    pass_filenames: false

# A linter for Golang
- repo: https://github.com/golangci/golangci-lint
  rev: 8f3b0c7ed018e57905fbd873c697e0b1ede605a5  # frozen: v2.11.4
  hooks:
  - id: golangci-lint

# Other pre-commit hooks for golang:
#   *-mod hooks run on the MODULE of each staged Go files.
#   *-repo-mod hooks run on each MODULE in the repository. This allows us to add multiple go modules to this repo.
#   *-repo hooks only run in the REPOSITORY root folder.
# These hooks automatically run on staged Go files, go.mod and go.sum.
# Other staged files shouldn't trigger these hooks.
# Documentation: https://github.com/TekWizely/pre-commit-golang/blob/v1.0.0-rc.1/README.md.
- repo: https://github.com/tekwizely/pre-commit-golang
  rev: a701af726d456597f5b0c3b55af615451489ceeb  # frozen: v0.8.3-rc.4
  hooks:
  - id: go-build-mod
  - id: go-build-repo-mod
    #
    # Go Mod Tidy
    #
  - id: go-mod-tidy
  - id: go-mod-tidy-repo
    #
    # Go Test
    #
  - id: go-test-mod
  - id: go-test-repo-mod
    #
    # Go Vet
    #
  - id: go-vet-mod
  - id: go-vet-repo-mod
    #
    # Go formatters
    #
  - id: go-fmt
  - id: go-fmt-repo
