/* Copyright (c) 2024 - 2024, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("test_policy", component_id, "") :-
    check_passed(component_id, "mcn_build_as_code_1"),
    check_passed(component_id, "mcn_build_script_1"),
    check_passed(component_id, "mcn_build_service_1"),
    check_passed(component_id, "mcn_version_control_system_1"),
    check_failed(component_id, "mcn_find_artifact_pipeline_1"),
    check_failed(component_id, "mcn_provenance_available_1"),
    check_failed(component_id, "mcn_provenance_derived_commit_1"),
    check_failed(component_id, "mcn_provenance_derived_repo_1"),
    check_failed(component_id, "mcn_provenance_expectation_1"),
    check_failed(component_id, "mcn_provenance_level_three_1"),
    check_failed(component_id, "mcn_provenance_witness_level_one_1"),
    check_failed(component_id, "mcn_trusted_builder_level_three_1"),
    is_repo_url(component_id, "https://github.com/onu-ui/onu-ui").

apply_policy_to("test_policy", component_id) :-
    is_component(component_id, "pkg:github.com/onu-ui/onu-ui@e3f2825c3940002a920d65476116a64684b3d95e").
