/* Copyright (c) 2024 - 2024, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("gh_witness_provenance_policy", component_id, "Policy for github Maven project with witness provenances") :-
    check_passed(component_id, "mcn_provenance_expectation_1").

apply_policy_to("gh_witness_provenance_policy", component_id) :-
    is_repo(
      _,  // repo_id
      "github.com/behnazh-w/example-maven-app",  // http URL to the repo but without the "http://"
      component_id
    ).
