/* Copyright (c) 2024 - 2024, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("test_policy", component_id, "") :-
    check_passed(component_id, "mcn_repo_verification_1").

apply_policy_to("test_policy", component_id) :-
    is_component(component_id, "pkg:maven/org.neo4j/cypher-parser-common@5.21.2").
