/* Copyright (c) 2024 - 2024, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("test_policy", component_id, "") :-
    check_passed(component_id, "mcn_version_control_system_1"),
    is_repo_url(component_id, "https://github.com/avaje/avaje-prisms").

apply_policy_to("test_policy", component_id) :-
    is_component(component_id, "pkg:maven/io.avaje/avaje-prisms@1.1").
