/* Copyright (c) 2025 - 2025, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("has-verified-provenance-toga", component_id, "Require a verified provenance file for toga.") :-
    check_passed(component_id, "mcn_provenance_derived_repo_1"),
    check_passed(component_id, "mcn_provenance_derived_commit_1"),
    check_passed(component_id, "mcn_provenance_verified_1").

apply_policy_to("has-verified-provenance-toga", component_id) :-
    is_component(component_id, purl),
    match("pkg:pypi/toga@.*", purl).
