# Copyright (c) 2025 - 2025, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

"""This module contains the logic to generate a build spec in Reproducible Central format."""

import logging
import shlex
from collections.abc import Mapping
from importlib import metadata as importlib_metadata

from macaron.build_spec_generator.build_command_patcher import PatchCommandBuildTool, PatchValueType, patch_commands
from macaron.build_spec_generator.internal_build_info import InternalBuildInfo
from macaron.build_spec_generator.jdk_finder import find_jdk_version_from_central_maven_repo
from macaron.build_spec_generator.jdk_version_normalizer import normalize_jdk_version

logger: logging.Logger = logging.getLogger(__name__)

# We use a subset of available config options from
# https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/doc/BUILDSPEC.md
# An example:
#   https://github.com/jvm-repo-rebuild/reproducible-central/blob/master/content/com/google/guava/guava-32.0.0-android.buildspec
# About this template
#   - Because the Reproducible-Central build spec is a bash script by itself, we can use
#     Bash comment syntax.
#   - We only work with git repository and its commit hash. Therefore `gitRepo` and `gitTag` are used only.
#     Even though it's called gitTag, a commit hash would work.
#     https://github.com/jvm-repo-rebuild/reproducible-central/blob/46de9b405cb30ff94effe0ba47c1ebecc5a1c17e/bin/includes/fetchSource.sh#L59C1-L59C72
STRING_TEMPLATE = """# Copyright (c) 2025, Oracle and/or its affiliates.
# Generated by Macaron version {macaron_version}

{extra_comment}

groupId={group_id}
artifactId={artifact_id}
version={version}

gitRepo={git_repo}

gitTag={git_tag}

tool={tool}
jdk={jdk}

newline={newline}

command="{command}"

buildinfo={buildinfo}
"""


def remove_shell_quote(cmd: list[str]) -> list[str]:
    """Remove shell quotes from a shell command.

    Parameters
    ----------
    cmd: list[str]
        The shell command as list of string.

    Returns
    -------
    list[str]
        The shell command with all quote removed.

    Examples
    --------
    >>> cmd = "mvn -f fit/core-reference/pom.xml verify '-Dit.test=RESTITCase' '-Dmodernizer.skip=true' '-Drat.skip=true'"
    >>> remove_shell_quote(cmd.split())
    ['mvn', '-f', 'fit/core-reference/pom.xml', 'verify', '-Dit.test=RESTITCase', '-Dmodernizer.skip=true', '-Drat.skip=true']
    """
    return shlex.split(" ".join(cmd))


def _get_extra_comments(comments: list[str]) -> str:
    """Generate the shell comments for adding additional information into the RC-build spec."""
    shell_comments = [f"# {comment}" for comment in comments]
    return "\n".join(shell_comments)


def _get_build_command_sequence(cmds_sequence: list[list[str]]) -> str:
    """Return a build command sequence as a string.

    The build commands in the sequence will be && together, because RC's build spec
    is a shell script.
    """
    result = ""
    if not cmds_sequence:
        return result

    result += " ".join(remove_shell_quote(cmds_sequence[0]))
    for cmd in cmds_sequence[1:]:
        result += f"&& {' '.join(remove_shell_quote(cmd))}"

    return result


def _get_build_spec_build_tool_name(lookup_build_tool_name: str) -> str | None:
    """Return the RC build tool name from the build tool name obtained from Macaron database."""
    if lookup_build_tool_name == "maven":
        return "mvn"

    if lookup_build_tool_name == "gradle":
        return "gradle"

    return None


def _get_default_build_command(lookup_build_tool_name: str) -> str | None:
    """Return a default build command for the corresponding build tool name discovered by Macaron."""
    if lookup_build_tool_name == "maven":
        return "mvn clean package"

    if lookup_build_tool_name == "gradle":
        return "./gradlew clean assemble publishToMavenLocal"

    return None


# Room for improvements for this function
# Refactor the logic to determine the default build tool to a separated function
# Defining the mapping used to format the template string happens multiple times with
# some minor differences. Can we refactor this to a function ?
def gen_reproducible_central_build_spec(
    build_info: InternalBuildInfo,
    patches: Mapping[
        PatchCommandBuildTool,
        Mapping[str, PatchValueType | None],
    ],
) -> str | None:
    """Return the content of a Reproducible Central Buildspec File.

    The Reproducible Central Buildspec File Format can be found here:
    https://github.com/jvm-repo-rebuild/reproducible-central/blob/e1708dd8dde3cdbe66b0cec9948812b601e90ba6/doc/BUILDSPEC.md#format

    This function will perform validation of the input PURL to make sure it has enough information for
    generating the output BuildSpec.

    This function will use the information available in ``build_info`` to populate the file.
    For example, the GAV coordinate can be obtained from ``build_info.purl``.

    Parameters
    ----------
    build_info: InternalBuildInfo
        The instance of InternalBuildInfo for the target we want to generate the Buildspec for.
    patches: Mapping[PatchCommandBuildTool, Mapping[str, PatchValueType | None]]
        The patches to apply to the build commands in ``build_info`` before being populated in
        the output Buildspec.

    Returns
    -------
    str | None
        The content of the Buildspec as string or None if there is an error.
        The errors that can happen are: 1. The input PURL is invalid, 2. There is no supported build tool
        for this PURL, 3. Failed to patch the build commands using the provided ``patches``.
    """
    extra_comments = []

    purl = build_info.purl

    # Validate if the PURL has enough information
    group = purl.namespace
    artifact = purl.name
    version = purl.version
    if group is None or version is None:
        logger.error("Missing group and/or version for Maven purl %s.", purl.to_string())
        return None

    extra_comments.append(f"Input PURL - {purl}")

    # The build tool from the build tool check table is found by checking the build configs.
    # We use this as the default build tool if we cannot find any build commands from the build-related checks.
    build_tool_facts = build_info.build_tool_facts
    default_build_tool_name = None
    for fact in build_info.build_tool_facts:
        if fact.build_tool_name in {"gradle", "maven"} and fact.language in {"java"}:
            # TODO: think about what to do if many build tools are discovered for a single project.!!!
            default_build_tool_name = fact.build_tool_name
            break
    if not default_build_tool_name:
        logger.error(
            "The PackageURL %s doesn't have any build tool that we support. It has %s.",
            purl.to_string(),
            [(fact.build_tool_name, fact.language) for fact in build_tool_facts],
        )
        return None

    build_spec_build_tool_name = _get_build_spec_build_tool_name(default_build_tool_name)

    if build_info.generic_build_command_facts:
        build_fact = build_info.generic_build_command_facts[0]
        lookup_build_command = build_fact.command
        extra_comments.append(f"The lookup build command: {lookup_build_command}")

        patched_build_commands = patch_commands(
            cmds_sequence=[lookup_build_command],
            patches=patches,
        )
        if not patched_build_commands:
            logger.error("Failed to patch command %s with patch %s", lookup_build_command, patches)
            return None

        extra_comments.append(f"Applied patched {patches}.")

        lookup_jdk_vers = build_fact.language_versions
        if lookup_jdk_vers:
            lookup_jdk_ver = lookup_jdk_vers.pop()
            extra_comments.append(f"Jdk version from lookup build command {lookup_jdk_ver}.")
            return STRING_TEMPLATE.format_map(
                {
                    "macaron_version": importlib_metadata.version("macaron"),
                    "extra_comment": _get_extra_comments(extra_comments),
                    "group_id": group,
                    "artifact_id": artifact,
                    "version": version,
                    "git_repo": build_info.repository.remote_path,
                    "git_tag": build_info.repository.commit_sha,
                    "tool": build_spec_build_tool_name,
                    "jdk": normalize_jdk_version(lookup_jdk_ver),
                    "newline": "lf",
                    "command": _get_build_command_sequence(patched_build_commands),
                    "buildinfo": f"target/{artifact}-{version}.buildinfo",
                }
            )

        extra_comments.append(f"No JDK version found from lookup result {patches}.")

        jdk_from_jar = find_jdk_version_from_central_maven_repo(
            group_id=purl.name,
            artifact_id=group,
            version=version,
        )
        if jdk_from_jar:
            extra_comments.append(f"Found JDK version from jar {jdk_from_jar}.")
            return STRING_TEMPLATE.format_map(
                {
                    "macaron_version": importlib_metadata.version("macaron"),
                    "extra_comment": _get_extra_comments(extra_comments),
                    "group_id": group,
                    "artifact_id": artifact,
                    "version": version,
                    "git_repo": build_info.repository.remote_path,
                    "git_tag": build_info.repository.commit_sha,
                    "tool": build_spec_build_tool_name,
                    "jdk": normalize_jdk_version(jdk_from_jar),
                    "newline": "lf",
                    "command": _get_build_command_sequence(patched_build_commands),
                    "buildinfo": f"target/{artifact}-{version}.buildinfo",
                }
            )

        extra_comments.append("Use default JDK version 8.")
        return STRING_TEMPLATE.format_map(
            {
                "macaron_version": importlib_metadata.version("macaron"),
                "extra_comment": _get_extra_comments(extra_comments),
                "group_id": group,
                "artifact_id": artifact,
                "version": version,
                "git_repo": build_info.repository.remote_path,
                "git_tag": build_info.repository.commit_sha,
                "tool": build_spec_build_tool_name,
                "jdk": "8",
                "newline": "lf",
                "command": _get_build_command_sequence(patched_build_commands),
                "buildinfo": f"target/{artifact}-{version}.buildinfo",
            }
        )

    default_build_command = _get_default_build_command(default_build_tool_name)
    if not default_build_command:
        logger.critical(
            "The default build command %s is not supported for getting default build command.",
            default_build_tool_name,
        )
        return None

    patched_build_commands = patch_commands(
        cmds_sequence=[default_build_command.split()],
        patches=patches,
    )

    if not patched_build_commands:
        logger.error("Failed to patch default build command %s with patch %s", default_build_command, patches)
        return None

    extra_comments.append(f"Use default JDK version 8 and default build command {default_build_command}.")

    return STRING_TEMPLATE.format_map(
        {
            "macaron_version": importlib_metadata.version("macaron"),
            "extra_comment": _get_extra_comments(extra_comments),
            "group_id": group,
            "artifact_id": artifact,
            "version": version,
            "git_repo": build_info.repository.remote_path,
            "git_tag": build_info.repository.commit_sha,
            "tool": build_spec_build_tool_name,
            "jdk": "8",
            "newline": "lf",
            "command": _get_build_command_sequence(patched_build_commands),
            "buildinfo": f"target/{artifact}-{version}.buildinfo",
        }
    )
