# Copyright (c) 2026 - 2026, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

"""Recommendation helpers for GitHub Actions security findings.

This module centralizes user-facing remediation guidance for findings generated by
GitHub Actions security analysis checks.
"""

from __future__ import annotations

import re
from dataclasses import dataclass

from macaron.errors import GitTagError
from macaron.slsa_analyzer.git_service.api_client import GhAPIClient
from macaron.slsa_analyzer.git_url import find_highest_git_tag, get_tags_via_git_remote, is_commit_hash

UNPINNED_ACTION_RE = re.compile(
    r"^(?:unpinned-third-party-action:\s*)?(?:\[step-line=(?P<line>\d+)\]\s*)?(?P<action>[^@\s]+)@(?P<version>[^\s]+)$"
)


@dataclass(frozen=True)
class Recommendation:
    """Normalized recommendation payload for a finding.

    Attributes
    ----------
    message : str
        Human-readable recommendation text.
    recommended_ref : str | None
        Optional pinned reference suggestion, such as ``owner/repo@<sha>``.
    """

    message: str
    recommended_ref: str | None = None


def recommend_for_unpinned_action(
    action_name: str, resolved_sha: str | None = None, resolved_tag: str | None = None
) -> Recommendation:
    """Create a recommendation for an unpinned third-party action.

    Parameters
    ----------
    action_name : str
        GitHub Action identifier in the form ``owner/repo``.
    resolved_sha : str | None, optional
        Resolved commit SHA for the action ref if available.
    resolved_tag : str | None, optional
        Tag corresponding to ``resolved_sha`` when available.

    Returns
    -------
    Recommendation
        Recommendation containing pinning guidance and a suggested immutable
        action reference.
    """
    if resolved_sha and resolved_tag:
        recommended_ref = f"{action_name}@{resolved_sha} # {resolved_tag}"
    elif resolved_sha:
        recommended_ref = f"{action_name}@{resolved_sha}"
    else:
        recommended_ref = "Unable to resolve automatically"
    return Recommendation(
        message="Pin this third-party action to a 40-character commit SHA.",
        recommended_ref=recommended_ref,
    )


def parse_unpinned_action_issue(issue: str) -> tuple[str, str] | None:
    """Parse an unpinned third-party action reference from issue text.

    Parameters
    ----------
    issue : str
        Raw issue text emitted by workflow security analysis.

    Returns
    -------
    tuple[str, str] | None
        Parsed ``(action_name, action_version)`` when the issue matches
        ``owner/repo@ref`` format for a third-party action. ``None`` otherwise.
    """
    match = UNPINNED_ACTION_RE.fullmatch(issue.strip())
    if not match:
        return None
    action = match.group("action")
    version = match.group("version")
    if action.startswith("./"):
        return None
    if "/" not in action:
        return None
    return action, version


def resolve_action_ref_to_sha(api_client: object, action_name: str, action_version: str) -> str | None:
    """Resolve an action reference to an immutable commit SHA.

    Parameters
    ----------
    api_client : object
        API client instance used for GitHub API calls.
    action_name : str
        GitHub Action identifier in the form ``owner/repo``.
    action_version : str
        Action ref currently used by the workflow.

    Returns
    -------
    str | None
        The resolved commit SHA if resolution succeeds; otherwise ``None``.
    """
    if not isinstance(api_client, GhAPIClient):
        return None
    if not action_name or not action_version:
        return None
    if is_commit_hash(action_version):
        # Normalize short SHAs by resolving them through the API.
        return (
            action_version
            if len(action_version) == 40
            else api_client.get_commit_sha_from_ref(action_name, action_version)
        )
    return api_client.get_commit_sha_from_ref(action_name, action_version)


def resolve_action_ref_to_tag(action_name: str, resolved_sha: str | None, action_version: str = "") -> str | None:
    """Resolve a commit SHA to a corresponding Git tag for an action repository.

    Parameters
    ----------
    action_name : str
        GitHub Action identifier in the form ``owner/repo``.
    resolved_sha : str | None, optional
        Resolved commit SHA for the action ref.
    action_version : str, optional
        Original action version/ref. If this exact ref is a tag on the same
        commit, it is preferred.

    Returns
    -------
    str | None
        The corresponding tag name if found; otherwise ``None``.
    """
    if not action_name or not resolved_sha:
        return None
    tags = get_tags_via_git_remote(f"https://github.com/{action_name}")
    if not tags:
        return None

    matching_tags = [tag for tag, tag_sha in tags.items() if tag_sha == resolved_sha]
    if not matching_tags:
        return None
    if action_version and action_version in matching_tags:
        return action_version
    try:
        return find_highest_git_tag(set(matching_tags))
    except GitTagError:
        return matching_tags[0]


def recommend_for_workflow_issue(issue: str) -> Recommendation:
    """Map a workflow issue string to a remediation recommendation.

    Parameters
    ----------
    issue : str
        Issue string emitted by workflow security analysis.

    Returns
    -------
    Recommendation
        Recommendation message corresponding to the detected issue category.
    """
    if issue.startswith("sensitive-trigger:"):
        return Recommendation("Add strict event gating (actor allowlist, branch filters, and conditional checks).")
    if issue.startswith("privileged-trigger:"):
        return Recommendation("Avoid pull_request_target for untrusted code paths; use pull_request where possible.")
    if issue.startswith("missing-permissions:"):
        return Recommendation("Define explicit least-privilege permissions at workflow or job scope.")
    if issue.startswith("overbroad-permissions:"):
        return Recommendation("Reduce permissions to read-only scopes unless write access is strictly required.")
    if issue.startswith("untrusted-fork-code:"):
        return Recommendation("Do not checkout PR head refs in privileged contexts; validate source and actor first.")
    if issue.startswith("persist-credentials:"):
        return Recommendation("Set persist-credentials: false for checkout unless later git pushes are required.")
    if issue.startswith("remote-script-exec:"):
        return Recommendation("Avoid curl|bash patterns; pin script digests or vendor reviewed scripts in-repo.")
    if issue.startswith("pr-target-untrusted-checkout:"):
        return Recommendation("Never combine pull_request_target with checkout of PR-controlled refs.")
    if issue.startswith("potential-injection:"):
        return Recommendation("Treat GitHub context data as untrusted input; quote/sanitize before shell execution.")
    return Recommendation("Review this workflow finding and apply least-privilege hardening controls.")


def recommend_for_osv_vulnerability(action_name: str, action_version: str) -> Recommendation:
    """Create a recommendation for a vulnerable GitHub Action version.

    Parameters
    ----------
    action_name : str
        GitHub Action identifier in the form ``owner/repo``.
    action_version : str
        Action ref currently used by the workflow.

    Returns
    -------
    Recommendation
        Recommendation encouraging upgrade to a non-vulnerable release and
        subsequent pinning to a commit SHA.
    """
    return Recommendation(
        message=(
            f"Upgrade `{action_name}` from `{action_version}` to a non-vulnerable release, "
            "then pin the selected version to a commit SHA."
        ),
        recommended_ref=None,
    )
