# Copyright (c) 2026 - 2026, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

"""Recommendation helpers for GitHub Actions security findings.

This module centralizes user-facing remediation guidance for findings generated by
GitHub Actions security analysis checks.
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class Recommendation:
    """Normalized recommendation payload for a finding.

    Attributes
    ----------
    message : str
        Human-readable recommendation text.
    recommended_ref : str | None
        Optional pinned reference suggestion, such as ``owner/repo@<sha>``.
    """

    message: str
    recommended_ref: str | None = None


def recommend_for_unpinned_action(action_name: str, resolved_sha: str | None = None) -> Recommendation:
    """Create a recommendation for an unpinned third-party action.

    Parameters
    ----------
    action_name : str
        GitHub Action identifier in the form ``owner/repo``.
    resolved_sha : str | None, optional
        Resolved commit SHA for the action ref if available.

    Returns
    -------
    Recommendation
        Recommendation containing pinning guidance and a suggested immutable
        action reference.
    """
    recommended_ref = f"{action_name}@{resolved_sha}" if resolved_sha else f"{action_name}@<40-char-commit-sha>"
    return Recommendation(
        message="Pin this third-party action to a full 40-character commit SHA to prevent tag drift or takeover risk.",
        recommended_ref=recommended_ref,
    )


def recommend_for_workflow_issue(issue: str) -> Recommendation:
    """Map a workflow issue string to a remediation recommendation.

    Parameters
    ----------
    issue : str
        Issue string emitted by workflow security analysis.

    Returns
    -------
    Recommendation
        Recommendation message corresponding to the detected issue category.
    """
    if issue.startswith("sensitive-trigger:"):
        return Recommendation("Add strict event gating (actor allowlist, branch filters, and conditional checks).")
    if issue.startswith("privileged-trigger:"):
        return Recommendation("Avoid pull_request_target for untrusted code paths; use pull_request where possible.")
    if issue.startswith("missing-permissions:"):
        return Recommendation("Define explicit least-privilege permissions at workflow or job scope.")
    if issue.startswith("overbroad-permissions:"):
        return Recommendation("Reduce permissions to read-only scopes unless write access is strictly required.")
    if issue.startswith("untrusted-fork-code:"):
        return Recommendation("Do not checkout PR head refs in privileged contexts; validate source and actor first.")
    if issue.startswith("persist-credentials:"):
        return Recommendation("Set persist-credentials: false for checkout unless later git pushes are required.")
    if issue.startswith("remote-script-exec:"):
        return Recommendation("Avoid curl|bash patterns; pin script digests or vendor reviewed scripts in-repo.")
    if issue.startswith("pr-target-untrusted-checkout:"):
        return Recommendation("Never combine pull_request_target with checkout of PR-controlled refs.")
    if issue.startswith("potential-injection:"):
        return Recommendation("Treat GitHub context data as untrusted input; quote/sanitize before shell execution.")
    return Recommendation("Review this workflow finding and apply least-privilege hardening controls.")


def recommend_for_osv_vulnerability(action_name: str, action_version: str) -> Recommendation:
    """Create a recommendation for a vulnerable GitHub Action version.

    Parameters
    ----------
    action_name : str
        GitHub Action identifier in the form ``owner/repo``.
    action_version : str
        Action ref currently used by the workflow.

    Returns
    -------
    Recommendation
        Recommendation encouraging upgrade to a non-vulnerable release and
        subsequent pinning to a commit SHA.
    """
    return Recommendation(
        message=(
            f"Upgrade `{action_name}` from `{action_version}` to a non-vulnerable release, "
            "then pin the selected version to a commit SHA."
        ),
        recommended_ref=None,
    )
