/* Copyright (c) 2025 - 2025, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("test_policy", component_id, "") :-
    check_passed(component_id, "mcn_scm_authenticity_1"),
    is_repo_url(component_id, "https://github.com/IntellectualSites/Arkitektonika-Client"),
    build_tool_check(
        check_id,
        "gradle",
        _
    ),
    check_facts(check_id, _, component_id,_,_).

apply_policy_to("test_policy", component_id) :-
    is_component(component_id, "pkg:maven/com.intellectualsites.arkitektonika/Arkitektonika-Client@2.1.3").
