/* Copyright (c) 2024 - 2024, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("check-dependencies", component_id, "Check the dependencies of django@5.0.6.") :-
    is_component(component_id, _),
    transitive_dependency(component_id, sqlparse),
    is_component(sqlparse, sqlparse_purl),
    match("pkg:pypi/sqlparse@0.*", sqlparse_purl),
    transitive_dependency(component_id, asgiref),
    is_component(asgiref, asgiref_purl),
    match("pkg:pypi/asgiref@3.*", asgiref_purl),
    check_passed(component_id, "mcn_detect_malicious_metadata_1"),
    check_passed(sqlparse, "mcn_detect_malicious_metadata_1"),
    check_passed(asgiref, "mcn_detect_malicious_metadata_1").


apply_policy_to("check-dependencies", component_id) :-
    is_component(component_id, "pkg:pypi/django@5.0.6").
