/* Copyright (c) 2024 - 2024, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("all-pypi", component_id, "Check all the Python packages.") :-
    check_passed(component_id, "mcn_detect_malicious_metadata_1").

apply_policy_to("all-pypi", component_id) :-
    is_component(component_id, purl),
    match("pkg:pypi.*", purl).
