/* Copyright (c) 2025 - 2025, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("github_actions_vulns_repo", component_id, "GitHub Actions Vulnerability Detection (repo)") :-
  check_passed(component_id, "mcn_githubactions_vulnerabilities_1").

apply_policy_to("github_actions_vulns_repo", component_id) :-
  is_repo_url(component_id, "https://github.com/apache/logging-log4j2").
