/* Copyright (c) 2025 - 2025, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("github_actions_vulns_purl", component_id, "GitHub Actions Vulnerability Detection (purl)") :-
  check_passed(component_id, "mcn_githubactions_vulnerabilities_1").

apply_policy_to("github_actions_vulns_purl", component_id) :-
  is_component(component_id, purl),
  match("pkg:maven/org.apache.logging.log4j/log4j-core@.*", purl).
