# Copyright (c) 2026 - 2026, Oracle and/or its affiliates. All rights reserved.
# Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/.

# Run Macaron's policies and generate Verification Summary Attestation reports.
# See https://github.com/oracle/macaron

name: Run Macaron to check supply chain security issues
on:
  push:
    branches:
    - main
    paths:
    - .github/workflows/**
  pull_request:
    paths:
    - .github/workflows/**
  schedule:
  - cron: 20 15 * * 3
permissions:
  contents: read

jobs:
  run_macaron:
    runs-on: ubuntu-latest

    steps:

    - name: Check out repository
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      with:
        fetch-depth: 0
        persist-credentials: false

    # Check the GitHub Actions workflows in the repository for vulnerabilities.
    # Note: adjust the policy_purl to refer to your repository URL.
    - name: Run Macaron action
      id: run_macaron
      uses: oracle/macaron@4ddb55e3c9ef2c77b548be55c557078c4476fd9c # v0.24.0
      with:
        repo_path: ./
        policy_file: check-github-actions
        policy_purl: pkg:github.com/oracle/macaron@.*
        reports_retention_days: 3
