/* Copyright (c) 2024 - 2025, Oracle and/or its affiliates. All rights reserved. */
/* Licensed under the Universal Permissive License v 1.0 as shown at https://oss.oracle.com/licenses/upl/. */

#include "prelude.dl"

Policy("test_policy", component_id, "") :-
    check_passed(component_id, "mcn_build_as_code_1"),
    check_passed(component_id, "mcn_build_script_1"),
    check_passed(component_id, "mcn_build_service_1"),
    check_passed(component_id, "mcn_version_control_system_1"),
    check_passed(component_id, "mcn_provenance_available_1"),
    check_passed(component_id, "mcn_provenance_derived_repo_1"),
    check_passed(component_id, "mcn_build_tool_1"),
    build_tool_check(gradle_id, "gradle", "java"),
    check_facts(gradle_id, _, component_id,_,_),
    provenance_verified_check(_, build_level, _),
    build_level = 3,
    check_failed(component_id, "mcn_provenance_derived_commit_1"),
    check_failed(component_id, "mcn_provenance_witness_level_one_1"),
    check_failed(component_id, "mcn_trusted_builder_level_three_1"),
    is_repo_url(component_id, "https://github.com/micronaut-projects/micronaut-test"),
    // The GitHub API for some reasons does not return the steps information anymore.
    // Note that mcn_find_artifact_pipeline_1 fails because it returns UNKNOWN, in this case with low confidence.
    check_failed_with_confidence(component_id, "mcn_find_artifact_pipeline_1", confidence),
    confidence = 0.4,
    artifact_pipeline_check(
        apc_check_id,
        "https://github.com/micronaut-projects/micronaut-test/blob/0ffa4e86ee4311f744f1a2b8ccd740a15af3a52b/.github/workflows/release.yml",
        "release",
        "publish",
        _,
        1,  // From provenance.
        1,  // Run deleted.
        0   // Published before the code was committed.
    ),
    check_facts(apc_check_id, confidence, component_id,_,_).

apply_policy_to("test_policy", component_id) :-
    is_component(component_id, purl),
    match("pkg:maven/io.micronaut.test/micronaut-test-junit5@.*", purl).
